baseURL = "https://valentinachapellu.com"
title = "Valentina Chapellu"
copyright = "Copyright 2020 Valentina Chapellu"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# googleAnalytics = "UA-XXXX"
# DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/authors/valentina"
    weight = 0
  [[menu.main]]
    identifier = "resume"
    name = "My Resume"
    url = "/resume.pdf"
    weight = 0

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  author = "Valentina Chapellu"
  description = "User Experience Designer"
  # homepageImage = "images/vale.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss      = true
    twitter  = "https://twitter.com/valechapellu"
    linkedin = "https://www.linkedin.com/in/valentina-chapellu/"
    medium   = "https://medium.com/@valentina.chapellu"
    # email = "example@example.com"
    # facebook = "https://facebook.com"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    # github = "https://github.com"
    # weibo = "https://www.weibo.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  # [params.commento]
  #   enable = true
  #   url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

#baseurl = "/"
#title = "Valentina Chapellu"
## theme = "hugo-creative-portfolio-theme"
#theme = "hugo-theme-chunky-poster"
#languageCode = "en-us"
## Enable Google Analytics by entering your tracking code
#googleAnalytics = ""

#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 10
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 0
#  [[menu.main]]
#    identifier = "resume"
#    name = "My Resume"
#    url = "/resume.pdf"
#    weight = 0
#  [[menu.main]]
#    identifier = "portfolio"
#    name = "Portfolio"
#    url = "/portfolio/"
#    weight = 0

#[taxonomies]
#category = "categories"
#tag = "tags"
#series = "series"
#author = "authors"

#[params]
#  # Style options: default (pink), blue, green, pink, red, sea, violet
#  # Use custom.css for your custom styling
#  style = "violet"
#  description = "Describe your website"
#  copyright = "&copy;2020 Valentina Chapellu"
#  sidebarAbout = [
#    "User Experience Designer",
#    "I design user-centered experiences and business processes."
#  ]
#  # Contact page
#     # Since this template is static, the contact form uses www.formspree.io as a
#     # proxy. The form makes a POST request to their servers to send the actual
#     # email. Visitors can send up to a 1000 emails each month for free.
#     #
#     # What you need to do for the setup?
#     #
#     # - set your email address under 'email' below
#     # - upload the generated site to your server
#     # - send a dummy email yourself to confirm your account
#     # - click the confirm link in the email from www.formspree.io
#     # - you're done. Happy mailing!
#  email = ""

#    # Optional Matomo analytics (formerly piwik)
#      # [params.analytics.matomo]
#      #  URL = "https://stats.example.com"
#      #  ID = "42"
#      #  # Track all subdomains with "*.example.com" (Optional)
#      #  domain = "www.example.com"
#      #  # Optional integrity check hash
#      #  hash = ""


#  [params.social]
#  twitter       = "https://twitter.com/valechapellu"
#  linkedin      = "https://www.linkedin.com/in/valentina-chapellu/"
#  # facebook      = "full page or profile url in facebook"
#  # googleplus    = "full profile url in googleplus"
#  # email         = "email@example.com"
#  # stackoverflow = "full profile url in stackoverflow"
#  # instagram     = "full profile url in instagram"
#  # github        = "full profile url in github"
#  # youtube       = "full profile url in youtube"
#  # whatsapp      = "wa.me service link"
